version: '3.9'

services:

  db:
    image: mysql:8.4
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=db_sanctions
    ports:
      - "3310:3306"
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      - PMA_HOST:db
    ports:
      - "8030:80"
    depends_on:
      - db

volumes:
  db:

